### ISSUE TITLE
SENSU_API_PORT collides with a default Kubernetes variable

### ISSUE THREAD

**Issue by andrewhowdencom** [rounds/10M-Docker-Images#27]
NOTE: I'm talking about the Sensu container. 

This is more funny than an actual problem, but I figure it might be worth mentioning. 

Kubernetes establishes a series of environment variables it makes available in all containers, which contain information about how to connect to a given service declaration. 

The most straight forward service name for the container running in api mode is "sensu-api". This means that Kubernetes makes "SENSU_API_PORT" available in all containers - Including this one. This collides with the same variable used in the configuration template, and it explodes for nearly inexplicable reasons. 

https://github.com/rounds/10M-Docker-Images/blob/master/sensu/etc/sensu/conf.d/config.json.tmpl#L3

Not too sure if you want to do anything about this. For now, I'm just going to rename the service.

**Comment by oryband** [comment]
Hi @andrewhowdencom , and thanks for opening the issue.

This is indeed amusing. However, I think the solution you've offered is the best one. I'd like to keep the environment variables simple and readable, and consider renaming them just so they fit with a specific scheduler (k8s) bad practice. Renaming the service sounds better.

Thanks for filing this though - maybe other people will be stumped about this issue and the future - and this will solve it for them.

Cheers!
